.TH STM_utilities 8 "10 April 1999" "Debian GNU/Linux" "SVGATextMode Utilities"
.\" Copyright (c) 1999  Ron Lee.  All rights reserved.
.\" This text may be distributed under the terms of the GPL.
.\"
.SH NAME
STM_utilities \- helper programs supplied with SVGATextMode
.SH SYNOPSIS
.B STM_reset
.br
.B ClockProg
.br
.B getVGAreg
.br
.B getpalette
.br
.B setVGAreg
.br
.B setpalette
.br
.B set80
.SH "DESCRIPTION"
These utilities currently do not have manual pages.
.PP
see \fI/usr/doc/svgatextmode\fP for details about their use.

